### PR TITLE
fix: fix secret namespace hardcode

### PR DESCRIPTION
**Pull request by vutkin**

### CODE REVIEW

**Review by scholzj — COMMENTED** [review]
Thanks for the PR. That is a good cacth. However, you cannot change the already released files in `helm-charts/`. The changes need to be done to `packaging/helm-charts/` which is what will be used for the next release. Also, I don't think you should hardcode the version - tht is set during the release.

**Comment by vutkin** [comment]
Fixed

**Review by scholzj — COMMENTED** [review]
You still need to do the changes only in `packaging/helm-charts/` and not in `helm-charts/`.

**Comment by vutkin** [comment]
> You still need to do the changes only in `packaging/helm-charts/` and not in `helm-charts/`.

Done finally. I hope

**Review by scholzj — APPROVED** [review]
Great, thanks.

**Review by ppatierno — APPROVED** [review]

**Comment by scholzj** [comment]
Thanks for the PR. I will prepare the 0.4.1 release for it as well.

**Pull request merged**
