### PR TITLE
Delete mvnw scripts

### PR DESCRIPTION
**Pull request by fvaleri**

### CODE REVIEW

**Comment by scholzj** [comment]
Why should this be committed in? I think it should not be present in the repo.

**Comment by fvaleri** [comment]
Are these supposed to be downloaded automatically? I'm getting the following error:
```
./mvnw compile quarkus:dev
./mvnw: line 276: /Users/fvaleri/Documents/code/drain-cleaner/.mvn/wrapper/maven-wrapper.properties: No such file or directory
/Users/fvaleri/Documents/code/drain-cleaner/.mvn/wrapper/maven-wrapper.jar: No such file or directory
Error: Could not find or load main class org.apache.maven.wrapper.MavenWrapperMain
Caused by: java.lang.ClassNotFoundException: org.apache.maven.wrapper.MavenWrapperMain
```

**Comment by scholzj** [comment]
Hmm, maybe we should remove the `mvnw` files as well.

**Comment by fvaleri** [comment]
That's fine for me, as I always use my own Maven version. You mean both `mvnw` and `mvnw.cmd` right?

**Review by scholzj — APPROVED** [review]

**Review by Frawless — APPROVED** [review]

**Review by ppatierno — APPROVED** [review]
Totally agree, this mvnw stuff is just a useless thing for trying to improve other things :)

**Pull request merged**
